import '../globals.css';
import { Montserrat } from 'next/font/google';
import Navbar from '../../components/Navbar';

const montserrat = Montserrat({ subsets: ['latin'], variable: '--font-mont' });

export const metadata = {
  title: 'My Portfolio',
  description: 'Generated by Next + Sanity',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`w-full m-auto  ${montserrat.variable} font-mont bg-light dark:bg-dark`}
      >
        <Navbar />
        <main>{children}</main>
      </body>
    </html>
  );
}
