import '../globals.css';
import { Montserrat } from 'next/font/google';

import Navbar from '../../components/Navbar';
import Footer from '@/components/Footer';

const montserrat = Montserrat({ subsets: ['latin'], variable: '--font-mont' });

export const metadata = {
  title: 'My Portfolio',
  description: 'Generated by Next + Sanity',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`w-full mx-auto  ${montserrat.variable} font-mont bg-white dark:bg-[#15141C]`}
      >
        <div className="relative min-h-screen">
          <Navbar />

          <main className="pb-60">{children}</main>

          <Footer />
        </div>
      </body>
    </html>
  );
}
